-- Trazabilidad de reclamos: tabla de eventos + trigger de creacion + RPC de gestion.

CREATE TABLE IF NOT EXISTS public.reclamo_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reclamo_id bigint NOT NULL REFERENCES public.reclamos(id) ON DELETE CASCADE,
  estado_anterior public.reclamo_estado,
  estado_nuevo public.reclamo_estado,
  comentario text,
  creado_por uuid DEFAULT auth.uid(),
  fecha_creacion timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reclamo_eventos_reclamo
  ON public.reclamo_eventos (reclamo_id, fecha_creacion);

ALTER TABLE public.reclamo_eventos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin gestiona eventos de reclamos" ON public.reclamo_eventos;
CREATE POLICY "Admin gestiona eventos de reclamos"
  ON public.reclamo_eventos FOR ALL TO authenticated
  USING (public.es_admin())
  WITH CHECK (public.es_admin());

-- Evento automatico al crear un reclamo (corre como definer para que tambien
-- aplique cuando el reclamo lo crea un inquilino).
CREATE OR REPLACE FUNCTION public.log_reclamo_creacion()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.reclamo_eventos (reclamo_id, estado_anterior, estado_nuevo, comentario, creado_por)
  VALUES (NEW.id, NULL, NEW.estado, NULL, auth.uid());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_log_reclamo_creacion ON public.reclamos;
CREATE TRIGGER trg_log_reclamo_creacion
  AFTER INSERT ON public.reclamos
  FOR EACH ROW EXECUTE FUNCTION public.log_reclamo_creacion();

-- Gestion de un reclamo: cambia estado y/o agrega una nota, registrando el evento.
CREATE OR REPLACE FUNCTION public.gestionar_reclamo(
  p_reclamo_id bigint,
  p_estado_nuevo public.reclamo_estado DEFAULT NULL,
  p_comentario text DEFAULT NULL
) RETURNS public.reclamo_eventos
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_estado_actual public.reclamo_estado;
  v_comentario text;
  v_evento public.reclamo_eventos;
  v_cambia boolean;
BEGIN
  IF NOT public.es_admin() THEN
    RAISE EXCEPTION 'Solo un administrador puede gestionar reclamos.';
  END IF;

  SELECT estado INTO v_estado_actual
  FROM public.reclamos WHERE id = p_reclamo_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'El reclamo no existe.';
  END IF;

  v_comentario := NULLIF(btrim(COALESCE(p_comentario, '')), '');
  v_cambia := p_estado_nuevo IS NOT NULL AND p_estado_nuevo <> v_estado_actual;

  IF v_cambia THEN
    IF p_estado_nuevo NOT IN ('Pendiente','En Proceso','Revision','Resuelto') THEN
      RAISE EXCEPTION 'Estado no valido.';
    END IF;
    IF p_estado_nuevo = 'Pendiente' THEN
      RAISE EXCEPTION 'Un reclamo no puede volver al estado Pendiente.';
    END IF;

    UPDATE public.reclamos SET estado = p_estado_nuevo WHERE id = p_reclamo_id;

    INSERT INTO public.reclamo_eventos (reclamo_id, estado_anterior, estado_nuevo, comentario, creado_por)
    VALUES (p_reclamo_id, v_estado_actual, p_estado_nuevo, v_comentario, auth.uid())
    RETURNING * INTO v_evento;
  ELSE
    IF v_comentario IS NULL THEN
      RAISE EXCEPTION 'Escribi un comentario o eligi un estado distinto.';
    END IF;

    INSERT INTO public.reclamo_eventos (reclamo_id, estado_anterior, estado_nuevo, comentario, creado_por)
    VALUES (p_reclamo_id, v_estado_actual, NULL, v_comentario, auth.uid())
    RETURNING * INTO v_evento;
  END IF;

  RETURN v_evento;
END;
$$;

GRANT EXECUTE ON FUNCTION public.gestionar_reclamo(bigint, public.reclamo_estado, text) TO authenticated;

-- Backfill: evento de creacion para los reclamos que ya existian.
INSERT INTO public.reclamo_eventos (reclamo_id, estado_anterior, estado_nuevo, comentario, creado_por, fecha_creacion)
SELECT r.id, NULL, r.estado, NULL, NULL, r.fecha_creacion
FROM public.reclamos r
WHERE NOT EXISTS (SELECT 1 FROM public.reclamo_eventos e WHERE e.reclamo_id = r.id);
