-- Catálogo de garantes / fiadores y vínculo con contratos.

BEGIN;

CREATE TABLE IF NOT EXISTS public.garantes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_completo text NOT NULL,
  dni text NOT NULL,
  cuil text,
  email text,
  telefono text,
  calle text,
  barrio text,
  ciudad text NOT NULL DEFAULT 'Córdoba',
  empleador text,
  empleador_cuit text,
  legajo text,
  fecha_ingreso date,
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS garantes_dni_key ON public.garantes (dni);

CREATE TABLE IF NOT EXISTS public.contrato_garantes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id bigint NOT NULL REFERENCES public.contratos (id) ON DELETE CASCADE,
  garante_id bigint NOT NULL REFERENCES public.garantes (id) ON DELETE RESTRICT,
  orden smallint NOT NULL DEFAULT 1 CHECK (orden >= 1),
  UNIQUE (contrato_id, garante_id)
);

CREATE INDEX IF NOT EXISTS idx_contrato_garantes_contrato_id ON public.contrato_garantes (contrato_id);
CREATE INDEX IF NOT EXISTS idx_contrato_garantes_garante_id ON public.contrato_garantes (garante_id);

CREATE OR REPLACE FUNCTION public.bloquear_delete_garante_con_contrato_vigente()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.contrato_garantes cg
    JOIN public.contratos c ON c.id = cg.contrato_id
    WHERE cg.garante_id = OLD.id
      AND c.estado IN ('activo', 'programado')
  ) THEN
    RAISE EXCEPTION 'No se puede eliminar el garante porque tiene contratos vigentes'
      USING ERRCODE = 'P0001';
  END IF;

  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_bloquear_delete_garante_con_contrato_vigente ON public.garantes;
CREATE TRIGGER trg_bloquear_delete_garante_con_contrato_vigente
  BEFORE DELETE ON public.garantes
  FOR EACH ROW
  EXECUTE FUNCTION public.bloquear_delete_garante_con_contrato_vigente();

ALTER TABLE public.garantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contrato_garantes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin CRUD garantes" ON public.garantes;
CREATE POLICY "Admin CRUD garantes"
  ON public.garantes FOR ALL TO authenticated
  USING (public.es_admin())
  WITH CHECK (public.es_admin());

DROP POLICY IF EXISTS "Admin CRUD contrato_garantes" ON public.contrato_garantes;
CREATE POLICY "Admin CRUD contrato_garantes"
  ON public.contrato_garantes FOR ALL TO authenticated
  USING (public.es_admin())
  WITH CHECK (public.es_admin());

COMMIT;
